version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CZVLT_DEBUG=${CZVLT_DEBUG}
      - MONGO_PASS=${MONGO_PASS}
    ports:
      - 1488:1488
    networks:
      - session
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - 6739:6739
    volumes:
      - ${REDIS_HOME}:/bitnami/redis/data
    networks:
      - session
networks:
  session:
    driver: bridge

